In [0]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense,Embedding,LSTM,SpatialDropout1D
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
import re


In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
data=pd.read_csv('/content/drive/My Drive/Sentiment.csv')

In [0]:
data=data[['text','sentiment']]

In [33]:
data.head()

text sentiment
0  RT @NancyLeeGrahn: How did everyone feel about...   Neutral
1  RT @ScottWalker: Didn't catch the full #GOPdeb...  Positive
2  RT @TJMShow: No mention of Tamir Rice and the ...   Neutral
3  RT @RobGeorge: That Carly Fiorina is trending ...  Positive
4  RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  Positive

In [0]:
trr=[]
srr=[]
t=0
for i in data['sentiment']:
  if(i!="Neutral"):
    trr.append(data.iloc[t][0])
    srr.append(data.iloc[t][1])
  t+=1

In [0]:
from keras.models import Model
from keras.layers import Input

In [0]:
trr=[i.lower() for i in trr]
trr=[re.sub('[^a-zA-z0-9\s]','',x) for x in trr]
tokenizer = Tokenizer(num_words=2000, split=' ')
tokenizer.fit_on_texts(trr)
X = tokenizer.texts_to_sequences(trr)
X = pad_sequences(X)
Y=pd.get_dummies(srr).values

In [41]:
X[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  17, 282,
       250,   6, 811, 103, 171,  27, 135,   7,   1, 172,  13,   2, 232,
       715,  18], dtype=int32)

In [42]:
trr[1]

'rt robgeorge that carly fiorina is trending  hours after her debate  above any of the men in justcompleted gopdebate says shes on '

In [37]:
Y.shape

(10729, 2)

In [47]:
max_features=2000
embedded_dim=128
lstm_out=156
input_shape=(28,)
sentence_indices=Input(input_shape,dtype='int32')
embedding_layer=Embedding(max_features,embedded_dim)(sentence_indices)
lstm=LSTM(lstm_out,dropout=0.5)(embedding_layer)
y=Dense(2,activation='relu')(lstm)
model=Model(inputs=sentence_indices,outputs=y)
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')
model.summary()

Model: "model_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        (None, 28)                0         
_________________________________________________________________
embedding_10 (Embedding)     (None, 28, 128)           256000    
_________________________________________________________________
lstm_10 (LSTM)               (None, 156)               177840    
_________________________________________________________________
dense_10 (Dense)             (None, 2)                 314       
Total params: 434,154
Trainable params: 434,154
Non-trainable params: 0
_________________________________________________________________


In [0]:
srr

In [48]:
from sklearn.preprocessing import LabelEncoder
m1=LabelEncoder()
srr1=m1.fit_transform(srr)
srr1

array([1, 1, 1, ..., 1, 0, 1])

In [50]:
Y=pd.get_dummies(srr1).values
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
y_train

array([[1, 0],
       [0, 1],
       [1, 0],
       ...,
       [0, 1],
       [1, 0],
       [1, 0]], dtype=uint8)

In [0]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

In [0]:
xrr=model.predict(x_test)

In [0]:
from sklearn.metrics import accuracy_score

In [0]:
print(accuracy_score(xrr[0],y_test[0]))

In [0]:
print(model.evaluate(x_test,y_test,batch_size=32))

In [0]:
x_test.shape